version: '3.8'
services:
  app:
    container_name: springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mypostgresdb
  mypostgresdb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog-docker

#        version: '3.1'
#        services:
#          app:
#            container_name: springboot-postgresql
#            image: docker-blog-image
#            build: ./
#            ports:
#              - "8080:8080"
#            depends_on:
#              - clementinaDb
#          clementinaDb:
#            image: postgres
#            ports:
#              - "5433:5432"
#            environment:
#              - POSTGRES_PASSWORD=postProgress
#              - POSTGRES_USER=postgres
#              - POSTGRES_DB=dockerBlogDB